config/routes.rb
Rails.application.routes.draw do
  get 'trainings/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root "home#top"
  get 'home/registration'
  resources :user, only: [:show, :edit, :update]do
    member do
      get 'profile'
      patch 'profile_update'
      get 'logout'
      get 'friends'
      get 'search'
      get :following, :followers
        resources :trainings
        resources :tweets
        resources :mygyms, only: [:index, :create,:destroy,:edit,:update]
        resources :messages, only: [:index, :create]
        namespace :api do
          resources :messages, only: :index, defaults: { format: 'json' }
        end
    end
  end
  resources :relationships, only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :start_time, presence: true
  # def start_time
  #   self.start_time
  # end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_user
  def index
    @trainings = current_user.trainings
  end

  def show
    @training = current_user.trainings.find(params[:id])
  end

  def new
    @trainings = current_user.trainings
  end

  def edit
    @training = current_user.trainings.find(params[:id])
  end

  def update
    @training = current_user.trainings.find(params[:id])
    @training.update(update_params)
    redirect_to trainings_path(@user.id)
  end

  def create
    @training = current_user.trainings.new(training_memo)
    if @training.save
      redirect_to trainings_path(@user.id)
    else
      redirect_to new_training_path
    end
  end

  def destroy
    @trainings = current_user.trainings.find(params[:id])
    @trainings.destroy
    redirect_to trainings_path(@user.id)
  end


  private
  def training_memo
    params.permit(:start_time,:title, :content,:user_id)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:training).permit(:start_time,:title, :content,:user_id)
  end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/edit.html.haml
=render "home/header_login"
.training-memo__main
  .training-memo__main__title トレーニングメモ登録
  .training-memo__main__form
  = form_with model: @training, url: training_path,local:true do |f|
    .form-group
      = f.label :トレーニング日
      = f.date_field :start_time
    .form-group
      = f.label :タイトル
      = f.text_field :title,class:'form-group__input'
    .form-group
      = f.label :トレーニング内容
      = f.text_area :content, class:'form-group__textarea'
    .form-group
      %p.form-group__text--center
      = f.submit '登録', class: "btn-default btn-red", url: training_path ,method: :patch

app/views/trainings/index.html.haml
=render "home/header_login"
.trainings
  =link_to "記録する", new_training_path ,class:"training-edit"
  = month_calendar events: @trainings do |date,trainings|
    = date.day
    - trainings.each do |training|
      =link_to training.title,training_path(training.id)

app/views/trainings/new.html.haml
=render "home/header_login"
.training-memo__main
  .training-memo__main__title トレーニングメモ登録
  .training-memo__main__form
  = form_with model: @training, url: trainings_path,local:true do |f|
    .form-group
      = f.label :トレーニング日
      = f.date_field :start_time
    .form-group
      = f.label :タイトル
      = f.text_field :title,class:'form-group__input'
    .form-group
      = f.label :トレーニング内容
      = f.text_area :content, class:'form-group__textarea'
    .form-group
      %p.form-group__text--center
      = f.submit '登録', class: "btn-default btn-red", url: trainings_path ,method: :post

app/views/trainings/show.html.haml
=render "home/header_login"
.training-memo__main
  .training-memo__main__title トレーニングメモ
  %ul.content
    %li.trainings-detail
      =@training.start_time
      =link_to '編集', edit_training_path(@training.id),class:"detail"
      =link_to '削除', training_path,method: :delete,class:"detail"
      %br/
      =@training.title
      %br/
      = simple_format(@training.content)
      %br/