config/routes.rb
Rails.application.routes.draw do
  get 'trainings/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root "home#top"
  get 'home/registration'
  resources :user, only: [:show, :edit, :update]do
    member do
      get 'profile'
      patch 'profile_update'
      get 'logout'
      get 'friends'
      get 'search'
      get :following, :followers
        resources :trainings
        resources :tweets
        resources :mygyms, only: [:index, :create,:destroy,:edit,:update]
        resources :messages, only: [:index, :create]
        namespace :api do
          resources :messages, only: :index, defaults: { format: 'json' }
        end
    end
  end
  resources :relationships, only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :content, {presence:true,length:{maximum:290}}
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @gym=current_user.mygym
    @tweets=Tweet.all
    # @tweets=Tweet.all.page(params[:page]).per(10).order("created_at DESC")
  end

  def show
    @tweet = current_user.tweets.find(params[:id])
  end

  def new
  end

  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  def update
    @tweet = current_user.tweets.find(params[:id])
    @tweet.update(update_params) if @tweet.user_id == current_user.id
    redirect_to tweets_path(current_user.id)
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweets_path(current_user.id)
    else
      redirect_to new_tweet_path
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy if @tweet.user_id == current_user.id
    redirect_to tweets_path(current_user.id)
  end



private
  def tweet_params
    params.permit(:content,:user_id)
  end

  def update_params
    params.require(:tweet).permit(:content,:user_id)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.haml
=render "home/header_login"
.training-memo__main
  .training-memo__main__title つぶやき投稿
  .training-memo__main__form
  = form_with model: @tweet, url: tweet_path,method: :patch,local:true do |f|
    .form-group
      = f.label :"トレーニングやジムのことをつぶやこう!"
      = f.label :"*文字数制限:290文字"
      = f.text_area :content, class:'form-group__textarea'
    .form-group
      %p.form-group__text--center
      = f.submit 'つぶやく', class: "btn-default btn-red"

app/views/tweets/index.html.haml
=render "home/header_login"
.tweets
  .tweets__title
    MyGym:#{@gym.gym}
    =link_to "MyGym変更", edit_mygym_path ,class:"mygym-edit"
  .tweets__main
    =link_to "投稿する", new_tweet_path ,class:"tweet-edit"
    .tweets__main__contents
      -@tweets.each do |tweet|
        .tweets__main__contents__detail
          - if user_signed_in? && current_user.mygym.gym ==tweet.user.mygym.gym
            .tweets__main__contents__detail__side
              .tweets__main__contents__detail__avatar
                -if tweet.user.avatar.attached?
                  =image_tag (tweet.user.avatar),class:"image-circle"
                -else
                  =image_tag ("noimage.png"),class:"avatar-circle"
            .tweets__main__contents__detail__main
              .tweets__main__contents__detail__nickname
                =link_to tweet.user.nickname,user_path(tweet.user.id),class:"detail"
                - if user_signed_in? && current_user.id ==tweet.user_id
                  =link_to '編集', edit_tweet_path(tweet.id),class:"detail"
                  =link_to '削除', tweet_path(tweet.id),method: :delete,class:"detail"
              .tweets__main__contents__detail__content
                = simple_format(tweet.content)

app/views/tweets/new.html.haml
=render "home/header_login"
.training-memo__main
  .training-memo__main__title つぶやき投稿
  .training-memo__main__form
  = form_with model: @tweet, url: tweets_path,method: :post,local:true do |f|
    .form-group
      = f.label :"トレーニングやジムのことをつぶやこう!"
      = f.label :"*文字数制限:２９０文字"
      = f.text_area :content, class:'form-group__textarea'
    .form-group
      %p.form-group__text--center
      = f.submit 'つぶやく', class: "btn-default btn-red"