config/routes.rb
Rails.application.routes.draw do
  get 'trainings/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root "home#top"
  get 'home/registration'
  resources :user, only: [:show, :edit, :update]do
    member do
      get 'profile'
      patch 'profile_update'
      get 'logout'
      get 'friends'
      get 'search'
      get :following, :followers
        resources :trainings
        resources :tweets
        resources :mygyms, only: [:index, :create,:destroy,:edit,:update]
        resources :messages, only: [:index, :create]
        namespace :api do
          resources :messages, only: :index, defaults: { format: 'json' }
        end
    end
  end
  resources :relationships, only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      @user = current_user
      redirect_to user_path(@user.id)
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header_login.html.haml
.header
  .header__contents__top
    .header__contents__title
      =link_to "BulkFriends", root_path, class:"title"
  .header__contents__below
    .header__contents__below__logout
      =link_to "ログアウト", logout_user_path ,class:"logout"
  -# .header__contents__below
  -#   .header__contents__below__search
  -#     .header__contents__below__search__friends
  -#       %span.fas.fa-list-ul.icon
  -#       =link_to "友達を探す", "#", class:"search__friends"
  -#     .header__contents__below__search__gyms
  -#       %span.fas.fa-tag.icon
  -#       =link_to "ジムを探す", "#",class:"search__gyms"
  -#   .header__contents__below__personal
  -#     .header__contents__below__personal__traings
  -#       %span.fas.fa-heart.login__icon
  -#       =link_to "トレーニング記録","#",class:"traings"
  -#     .header__contents__below__personal__messages
  -#       %span.fas.fa-bell.login__icon
  -#       =link_to "メッセージ", "#",class:"messages"
  -#     .header__contents__below__personal__mygym
  -#       %span.fas.fa-check.login__icon
  -#       =link_to "マイジム", "#",class:"mygym"
  -#     .header__contents__below__personal__mypage
  -#       %span.fas.fa-user-circle.login__icon
  -#       =link_to "マイページ", "#",class:"mypage"

app/views/home/_header_unlogin.html.haml
.header
  .header__contents__top
    .header__contents__title
      =link_to "BulkFriends", root_path, class:"title"
  .header__contents__below
    .header__contents__below__about
      =link_to "About", "#", class:"about", id:"scroll_about"
    .header__contents__below__registration
      .header__contents__below__registration__new
        =link_to "新規会員登録", home_registration_path ,class:"registration"
      .header__contents__below__registration__login
        =link_to "ログイン", user_session_path ,class:"login"

app/views/home/registration.html.haml
=render "home/header_unlogin"
.registaration_index
  .registaration_index_container
    .registaration_index_container-main
      %h2.registaration_index__container__title
        新規会員登録
      .registration_contents
        =link_to new_user_registration_path, class: "btn-def--mail","data-turbolinks": false do
          %i.far.fa-envelope
          %span<>
          メールアドレスで登録する
        -# =link_to user_twitter_omniauth_authorize_path, method: :post, class: "btn-def--twitter" do
        -#   %i.fab.fa-twitter
        -#   %span<>
        -#   Twitterで登録する

app/views/home/top.html.haml
-# -if user_signed_in?
-#   =render "home/header_login"
-# -else
=render "home/header_unlogin"
.top
  .top_main
    .top_main_container
      %h1.top_main_title BulkFriends
      %h2.top_main_subtitle -Make Mascle,Make Friends-
  .top_about
    #scroll_about_target
    .top_about_container
      %h1.top_about_title 共に身体を鍛える友を作ろう
      %h2.top_about_title_sub 
        MyGym:ジムを登録
        %br/
        Traing:トレーニングを記録 
        %br/
        Friends:友達と共にトレーニング