config/routes.rb
Rails.application.routes.draw do
  get 'trainings/index'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  root "home#top"
  get 'home/registration'
  resources :user, only: [:show, :edit, :update]do
    member do
      get 'profile'
      patch 'profile_update'
      get 'logout'
      get 'friends'
      get 'search'
      get :following, :followers
        resources :trainings
        resources :tweets
        resources :mygyms, only: [:index, :create,:destroy,:edit,:update]
        resources :messages, only: [:index, :create]
        namespace :api do
          resources :messages, only: :index, defaults: { format: 'json' }
        end
    end
  end
  resources :relationships, only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 7 }, format: { with: /(?=.*\d+.*)(?=.*[a-zA-Z]+.*)./ }
  validates :introduction, length: { maximum: 290 }

  #アバター
  has_one_attached :avatar

  #友達機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  #メッセージ機能
  has_many :messages, dependent: :destroy
  has_many :sent_messages, through: :messages, source: :receive_user
  has_many :reverses_of_message, class_name: 'Message', foreign_key: 'receive_user_id'
  has_many :received_messages, through: :reverses_of_message, source: :user

  #トレーニングメモ機能
  has_many :trainings, dependent: :destroy

  #Mygym機能
  has_one :mygym, dependent: :destroy
  has_many :tweets, dependent: :destroy

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def matchers
    followings & followers
  end

  def self.search(nickname)
    if nickname
      User.where(['nickname LIKE ?', "%#{nickname}%"])
    else
      User.all
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit,:profile,:profile_update,:logout,:friends,:search]
#     before_action :set_address, only: [:edit, :update]

def show
  @relationship = Relationship.new
end

def edit
end

def logout
end

def friends
  @friends = current_user.matchers
end


def profile_update
  if @user.update(user_params)
    redirect_to user_path(@user.id)
  else
    render :profile
  end
end

def search
  @users = User.search(params[:search])
  @friends = current_user.matchers
end

private

def set_user
  @user = User.find(params[:id])
end

def user_params
  params.require(:user).permit(
    :nickname,
    :email,
    :password,
    :avatar,
    :introduction,
  )
end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
  end

  def create

    # if params[:sns_auth] == 'true'
    #   pass = Devise.friendly_token
    #   params[:user][:password] = pass
    #   params[:user][:password_confirmation] = pass
    # end

    # unless @user.valid?
    #   flash.now[:alert] = @user.errors.full_messages
    #   render :new and return
    # end
    @user = User.new(sign_up_params)
    if @user.save
      sign_in(:user, @user)
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_follow-following.html.haml
= link_to user_path(@user.id), class: "" do
  %li.friends__list
    .friends__avatar
      -if @user.avatar.attached?
        =image_tag @user.avatar, class:"avatar"
      -else
        =image_tag ("noimage.png"),class:"avatar"
    .friends__name
        = @user.name

app/views/user/friends.html.haml
=render "home/header_login"
.friends
  .friends__main
    Friends
    .friends__main__contents
      .friends__main__contents__search
        .friends__main__contents__search__title
          =form_with url: search_user_path, method: :get, id: "form1", local: true do |f|
            =f.text_field :search, {placeholder: "キーワードを入力",id: "sbox"}
            =f.submit "検索", id: "sbtn"
      .friends__main__contents__lists
        %ul.tab
          %li.select FRIENDS
          %li LIKE
          %li LIKED
        %ul.content
          %li.friends-list
            -@friends.each do |friend|
              .friend__line
                .line-name
                  =friend.nickname
                  =link_to '詳細', user_path(friend),class:"detail"
                .line-avatar
                  -if friend.avatar.attached?
                    =image_tag (friend.avatar),class:"line-image"
                  -else
                    =image_tag ("noimage.png"),class:"avatar"
                .line-introduction
                  =friend.introduction
          %li.hide
            -@user.followings.each do |following|
              .friend__line
                .line-name
                  =following.nickname
                  =link_to '詳細', user_path(following),class:"detail"
                .line-avatar
                  -if following.avatar.attached?
                    =image_tag (following.avatar),class:"line-image"
                  -else
                    =image_tag ("noimage.png"),class:"avatar"
                .line-introduction
                  =following.introduction
          %li.hide
            -@user.followers.each do |follower|
              .friend__line
                .line-name
                  =follower.nickname
                  =link_to '詳細', user_path(follower),class:"detail"
                .line-avatar
                  -if follower.avatar.attached?
                    =image_tag (follower.avatar),class:"line-image"
                  -else
                    =image_tag ("noimage.png"),class:"avatar"
                .line-introduction
                  =follower.introduction

app/views/user/logout.html.haml
.header
  .header__contents__top
    .header__contents__title
      =link_to "BulkFriends", root_path, class:"title"
.logout_index
  .logout_index_container
    .logout_index_container-main
      %h2.logout_main_title
        =link_to destroy_user_session_path, method: :delete, class:"logout_title" do
          ログアウト

app/views/user/profile.html.haml
=render "home/header_login"
.profile
  .profile__main
    %h1.profile__main__title
    プロフィール編集
    .profile__main__contents
      = form_with model: @user, url: profile_update_user_path ,method: :patch, local:true do |f|
        .form-group
          = f.label :ニックネーム
          %span.form-group__require 必須
          = f.text_field :nickname, class:'form-group__input'
        .form-group
          = f.label :メールアドレス
          %span.form-group__require 必須
          = f.email_field :email, {autofocus: true, autocomplete: "email",class:'form-group__input'}
        .form-group
          = f.label :パスワード
          %span.form-group__require 必須
          = f.password_field :password,{class:'form-group__input',id:"password"}
          %p.form-group__info ※ 英字と数字の両方を含めて設定してください
          .form-password-revelation-toggle
            .checkbox-default
              %input#reveal_password{type: "checkbox",class:"icon-check"}
              %label{for: "reveal_password"} パスワードを表示する
            .form-password-revelation-revealed-password-container
              %span.form-password-revelation-revealed-password
        .form-group
          = f.label :プロフィール写真
          = f.file_field :avatar
        -if @user.avatar.attached?
          =@user.avatar.purge
        .form-group
          = f.label :プロフィール
          = f.text_area :introduction, class:'form-group__textarea'
        .form-group
          %p.form-group__text--center
          = f.submit '変更する', class: "btn-default btn-red"

app/views/user/search.html.haml
=render "home/header_login"
.search
  .search__main
    Search Result
    .search__main__form
      =form_with url: search_user_path, method: :get, id: "form1", local: true do |f|
        =f.text_field :search, {placeholder: "キーワードを入力",id: "sbox"}
        =f.submit "検索", id: "sbtn"
    .search__main__result
      %ul.content
        %li.friends-list
          -@users.each do |user|
            .friend__line
              .line-name
                =user.nickname
                =link_to '詳細', user_path(user),class:"detail"
              .line-avatar
                -if user.avatar.attached?
                  =image_tag (user.avatar),class:"line-image"
                -else
                  =image_tag ("noimage.png"),class:"avatar"
              .line-introduction
                =user.introduction

app/views/user/show.html.haml
=render "home/header_login"
.mypage
  .mypage_top
    .mypage_top_container
      .mypage_top_container_avator
        .mypage_top_container_avator_main
          -if @user.avatar.attached?
            =image_tag @user.avatar, class:"avatar"
          -else
            =image_tag ("noimage.png"),class:"avatar"
      .mypage_top_container_info
        .mypage_top_container_info_name
          .mypage_top_container_info_name_detail
            %h1.plofile_name
              =@user.nickname
            -if current_user.id == @user.id
              .plofile_name_edit
                =link_to "プロフィール編集", profile_user_path ,class:"profile-edit"
            - else
              - if current_user.following?(@user)
                = form_with model: @relationship,url: relationship_path, method: :delete  do |f|
                  = button_tag type: 'submit', class: 'btn-liked',id: "unfollow_form" do
                    %i.fas.fa-heart.fa-3x
              - else
                = form_with model: @relationship do |f|
                  %div= hidden_field_tag :following_id, @user.id
                  = button_tag type: 'submit', class: 'btn-likes',id: "follow_form" do
                    %i.far.fa-heart.fa-3x
        .mypage_top_container_info_profile
          = simple_format(@user.introduction)
  .mypage_main
    -if current_user.id == @user.id
      .mypage_main_menus
        =link_to trainings_path(@user.id),class:"mypage_main_menus_trainings","data-turbolinks": false do
          .mypage_main_menus_trainings_details
            %h1.menus_title
              Trainings
        =link_to friends_user_path,class:"mypage_main_menus_friends","data-turbolinks": false do
          .mypage_main_menus_friends_details
            %h1.menus_title
              Friends
        =link_to messages_path,class:"mypage_main_menus_messages","data-turbolinks": false do
          .mypage_main_menus_messages_details
            %h1.menus_title
              Messages
        =link_to mygyms_path,class:"mypage_main_menus_mygym","data-turbolinks": false do
          .mypage_main_menus_mygym_details
            %h1.menus_title
              MyGYM
    -else
      -# .otherspage_main_menus
      -#   =link_to trainings_path,class:"otherspage_main_menus_trainings","data-turbolinks": false do
      -#     .otherspage_main_menus_trainings_details
      -#       %h1.menus_title
      -#         Trainings
      -#   .otherspage_main_menus_friends
      -#     .otherspage_main_menus_friends_details
      -#       %h1.menus_title
      -#         Friends
      -#   .otherspage_main_menus_messages
      -#     .otherspage_main_menus_messages_details
      -#       %h1.menus_title
      -#         Messages